# Generated by Django 5.0.6 on 2024-06-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='more_details_for_the_dedicated_page',
            field=models.TextField(default=' ', max_length=2500),
        ),
        migrations.AlterField(
            model_name='post',
            name='paragraph',
            field=models.TextField(max_length=250),
        ),
    ]
